---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lksclient-binding

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lksclient-binding
rules:
- apiGroups: ["clustercontroller.k8s.io"]
  resources: ["lkcontrollers"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lksclient
subjects:
- kind: ServiceAccount
  name: lksclient-binding
  namespace: default
roleRef:
  kind: ClusterRole
  name: lksclient-binding
  apiGroup: rbac.authorization.k8s.io
